name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  industrial_ci:
    strategy:
      fail-fast: false
      matrix:
        env:
          - {OS_NAME: ubuntu,
             OS_CODE_NAME: bionic,
             ROS_DISTRO: melodic,
             ROS_REPO: main,
             BADGE: melodic}
          - {OS_NAME: ubuntu,
             OS_CODE_NAME: focal,
             ROS_DISTRO: noetic,
             ROS_REPO: main,
             BADGE: noetic}
          - {OS_NAME: ubuntu,
             OS_CODE_NAME: focal,
             ROS_DISTRO: noetic,
             CLANG_FORMAT_VERSION: 8,
             CLANG_FORMAT_CHECK: file,
             BADGE: clang-format}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
